export const ROUTES = {
  Login: 'Login',
  Register: 'Register',
  DrawerNavigator: 'DrawerNavigator',
  Home: 'Home',
  AuthNavigator: 'AuthNavigator',
  Profile: 'Profile',
  About: 'About',
  Contact: 'Contact',
  Trip: 'Trip',
  Licence: 'Licence',
  Identity: 'Identity',
  SelectPath: 'SelectPath',
  CreatePath: 'CreatePath',
  RegisterNavigator: 'RegisterNavigator',
};
